version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: jcmongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /jumpcloud_interview_assignment/jumpcloud-escalations-engineer-assignment/mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
